In [1]:
#Import the required dataset needed 
import os
import pandas as pd
import sys
from IPython.display import display
from dis import dis
import geopandas
import pandas as pd
from shapely.wkt import loads

In [14]:
#Get the data from our folder and clean them up FOR area of burnt

path_AoB = []
for i in range(0, 10):
    path = os.path.abspath(os.path.join(os.getcwd(),
                                        '../Wildfires_Date_of_Burning_1559/data/ABoVE_DoB_201' + str(i)  + '.shp' ))
    path_AoB.append(path)

In [15]:
#Fire Charateristics Dataset
charateristics = []
for i in range(0, 10):
    path = os.path.abspath(os.path.join(os.getcwd(), '../Wildfires_Date_of_Burning_1559/data/ABoVE_DoB_MODIS_Active_Fires_201' + str(i)  + '.shp' ))
    charateristics.append(path)

In [16]:
def make_dataframes(aob_path, chracteristics_path):
    gdf_extents = []
    for path in aob_path:
        gdf_extents.append(geopandas.GeoDataFrame.from_file(path))
    
    gdf_locations = []
    for path in chracteristics_path:
        gdf_locations.append(geopandas.GeoDataFrame.from_file(path))

    gdf_aob = pd.concat(gdf_extents, axis = 0)
    gdf_characteristics = pd.concat(gdf_locations, axis = 0)

    # filter merged data for Alberta and BC
    gdf_aob_AB_BC = gdf_aob[(gdf_aob["REF_ID"].apply(lambda s : s[0:2] == "AB")) | 
                            (gdf_aob["REF_ID"].apply(lambda s : s[0:2] == "BC"))]

    gdf_characteristics_AB_BC = gdf_characteristics[(gdf_characteristics["REF_ID"].apply(lambda s : s[0:2] == "AB")) | 
                            (gdf_characteristics["REF_ID"].apply(lambda s : s[0:2] == "BC"))]

    return gdf_aob_AB_BC, gdf_characteristics_AB_BC

In [17]:
#Create the datadrame from our shapefiles
AoB,Charateristics = make_dataframes(path_AoB,  charateristics)

In [21]:
path_AoB = os.path.abspath(os.path.join(os.getcwd(), '../Wildfires_Date_of_Burning_1559/data/AoB.csv'))
charateristics =  os.path.abspath(os.path.join(os.getcwd(), '../Wildfires_Date_of_Burning_1559/data/Charateristics.csv'))

AoB.to_csv(path_AoB, index = False)
Charateristics.to_csv(charateristics, index = False)

In [22]:
#View Our Two Dataset
display(AoB.head())
display(Charateristics.head())

,UID_Fire,FD_Agency,REF_ID,date_src,Year,JD,Map_Date,geometry
43,193,CA,BC-2010-C10060,1AF,2010,152,2010-06-01,"POLYGON Z ((-1688364.429 1766761.124 0.000, -1..."
44,208,CA,BC-2010-C10258,1AF,2010,212,2010-07-31,"POLYGON Z ((-1765477.675 1801382.759 0.000, -1..."
45,215,CA,BC-2010-C10320,1AF,2010,214,2010-08-02,"POLYGON Z ((-1637226.554 1746616.851 0.000, -1..."
46,222,CA,BC-2010-C20018,1AF,2010,187,2010-07-06,"POLYGON Z ((-1764660.362 1676377.401 0.000, -1..."
47,245,CA,BC-2010-C20293,1AF,2010,212,2010-07-31,"POLYGON Z ((-1755143.000 1702585.419 0.000, -1..."

,YYYYMMDD,HHMM,sat,lat,lon,T21,T31,sample,FRP,conf,type,UID_Fire,Status,FD_Agency,REF_ID,geometry,dn
7,20100816,604,T,50.388,-127.290,307.3,293.0,918,9.3,71,0,547,primary,CA,BC-2010-V90985,POINT (-2143720.640 1647561.231),NaN
8,20100721,936,A,49.199,-124.104,317.4,286.1,44,110.9,95,0,541,primary,CA,BC-2010-V70506,POINT (-1992828.781 1429941.640),NaN
9,20100721,1114,A,49.201,-124.111,305.8,285.8,1229,32.3,66,0,541,primary,CA,BC-2010-V70506,POINT (-1993205.618 1430352.170),NaN
10,20100814,615,T,48.492,-124.029,301.9,290.2,548,5.1,45,0,538,primary,CA,BC-2010-V60945,POINT (-2019595.640 1356043.682),NaN
11,20100814,615,T,48.491,-124.043,357.2,294.9,549,84.1,100,0,538,primary,CA,BC-2010-V60945,POINT (-2020590.036 1356363.410),NaN